events {}

http {
    include       /etc/nginx/mime.types;
    charset       utf-8;

    server {
        listen       ${PORT};
        root         /app;
        index        index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
